future: true
permalink: /:title/
url: http://south270.github.io
name: South
author: South
qq: 634838533
email: liuyn56@mail2.sysu.edu.cn

duoshuo: South
beian: 
cnzz: 
weibo: 
github: south270
about: "这里是 South 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
